FROM centos

MAINTAINER qktong <qktong@qq.com>

RUN yum install -y \
    make \
    automake \
    autoconf \
    libtool \
    gcc \
    gcc-c++ \
    ncurses-devel \
    zlib-devel \
    pcre-devel \
    openssl-devel \
    libxslt-devel \
    gd-devel \
    perl-devel \
    perl-ExtUtils-Embed \
    geoip-devel \
    curl-devel \
    libxml2-devel \
    libpng-devel \
    && yum clean all